# DASHBOARD
from tests.pages import common

EXECUTION_DASHBOARD_TITLE = "Execution Dashboard"
OVERVIEW_DASHBOARD_TITLE = "Overview"
GLOBAL_SETTING_MENU = {"add"         : "Add Page",
                       "cre_prof"    : "Create Profile",
                       "cre_panel"   : "Create Panel",
                       "edit"        : "Edit",
                       "del"         : "Delete"}
DEFAULT_PANELS = {"Charts"      : ["Action Implementation By Status",
                                   "Test Case Execution Failure Trend",
                                   "Test Case Execution Results",
                                   "Test Case Execution Trend",
                                   "Test Module Execution Failure Trend",
                                   "Test Module Execution Results",
                                   "Test Module Execution Trend",
                                   "Test Module Implementation By Priority",
                                   "Test Module Implementation By Status",
                                   "Test Module Status per Assigned Users"],
                  "Indicators"  : ["Test Case Execution",
                                   "Test Module Execution",
                                   "Test Objective Execution"],
                  "Reports"     : ["Test Module Execution Results Report"],
                  "Heat Maps"   : ["Test Case Execution History",
                                   "Test Module Execution History"]}

# DATA PROFILES
DEFAULT_DATA_PROFILES = sorted(sum(DEFAULT_PANELS.values(), []))
DATA_PROFILE_FIELDS = ["General Settings",
                       "Display Fields",
                       "Sort Fields",
                       "Filter Fields",
                       "Statistic Fields",
                       "Display Sub-Fields",
                       "Sort Sub-Fields",
                       "Filter Sub-Fields",
                       "Statistic Sub-Fields"]
GENERAL_SETTINGS_DROPDOWN = {"Item Type"    : ["Test Modules",
                                              "Test Cases",
                                              "Test Objectives",
                                              "Data Sets",
                                              "Actions",
                                              "Interface Entities",
                                              "Test Results",
                                              "Test Case Results",
                                              "Test Suites",
                                              "Bugs"],
                             "Related Data" : {"Test Modules"       : ["None",
                                                                       "Related Test Results",
                                                                       "Related Bugs",
                                                                       "Related Test Cases"],
                                              "Test Cases"          : ["None",
                                                                       "Related Run Results",
                                                                       "Related Bugs",
                                                                       "Related Objectives",
                                                                       "Related Steps"],
                                              "Test Objectives"     : ["None",
                                                                       "Related Run Results",
                                                                       "Related Test Cases"],
                                              "Data Sets"           : ["None"],
                                              "Actions"             : ["None",
                                                                       "Action Arguments"],
                                              "Interface Entities"  : ["None",
                                                                       "Interface Elements"],
                                              "Test Results"        : ["None",
                                                                       "Related Bugs",
                                                                       "Related Test Modules",
                                                                       "Related Test Cases"],
                                              "Test Case Results"   : ["None"],
                                              "Test Suites"         : ["None"],
                                              "Bugs"                : ["None",
                                                                       "Related Test Results",
                                                                       "Related Test Modules",
                                                                       "Related Test Cases"]}}
